CREATE SEQUENCE  ASSIGNMENT_PATTERN_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE ASSIGNMENT_PATTERN
   (	"ID" NUMBER DEFAULT ASSIGNMENT_PATTERN_SEQUENCE."NEXTVAL" NOT NULL ENABLE, 
	"PATTERN_ID" NUMBER NOT NULL ENABLE, 
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ASSIGNMET_PATTERN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPIRIT_TAB"  ENABLE, 
	 CONSTRAINT "ASSIGNMET_PATTERN_FK1" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES ASSIGNMENT ("ID") ENABLE, 
	 CONSTRAINT "ASSIGNMET_PATTERN_FK2" FOREIGN KEY ("PATTERN_ID")
	  REFERENCES ACTIONPATTERNS ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPIRIT_TAB" ;

CREATE TABLE ASSIGNMENT_PATTERN_AUD
   (	"ID" NUMBER, 
	"PATTERN_ID" NUMBER, 
	"ASSIGNMENT_ID" NUMBER, 
	"REV" NUMBER(10,0) NOT NULL ENABLE, 
	"REVTYPE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPIRIT_TAB" ;

Grant all on SPIRIT.ASSIGNMENT_PATTERN_SEQUENCE to SPIRIT_FATCLIENT;
Grant all on SPIRIT.ASSIGNMENT_PATTERN to SPIRIT_FATCLIENT;
Grant all on SPIRIT.ASSIGNMENT_PATTERN_AUD to SPIRIT_FATCLIENT;