alter table study_stage rename to stage;
alter table study_stage_aud rename to stage_aud;
DROP TABLE study_action;
DROP TABLE study_action_aud;
alter table study_actionpatterns rename to actionpatterns;
alter table study_actionpatterns_aud rename to actionpatterns_aud;
alter table study_administration rename to administration;
alter table study_administration_aud rename to administration_aud;
alter table study_execution_details rename to execution_details;
alter table study_execution_details_aud rename to execution_details_aud;
alter table study_subgroup rename to subgroup;
alter table study_subgroup_aud rename to subgroup_aud;
alter table study_subgroup_biotype_metadatavalue rename to subgroup_biotype_metadatavalue;
alter table study_subgroup_biotype_metadatavalue_aud rename to subgroup_biotype_metadatavalue_aud;
alter table study_group_biotype_metadatavalue rename to group_biotype_metadatavalue;
alter table study_group_biotype_metadatavalue_aud rename to group_biotype_metadatavalue_aud;
alter table study_namedtreatment rename to namedtreatment;
alter table study_namedtreatment_aud rename to namedtreatment_aud;
alter table study_phase rename to phase;
alter table study_phase_aud rename to phase_aud;
alter table study_property rename to property;
alter table study_property_aud rename to property_aud;
alter table study_sampling rename to namedsampling;
alter table study_sampling_aud rename to namedsampling_aud;
alter table study_schedule rename to schedule;
alter table study_schedule_aud rename to schedule_aud;
alter table study_schedule_phase rename to schedule_phase;
alter table study_schedule_phase_aud rename to schedule_phase_aud;
alter table study_stage_biotype_metadatavalue rename to stage_biotype_metadatavalue;
alter table study_stage_biotype_metadatavalue_aud rename to stage_biotype_metadatavalue_aud;
alter table assay rename column assay_id to id;
alter table assay rename column assay_name to name;
alter table assay rename column assay_type to type;
alter table assay_aud rename column assay_id to id;
alter table assay_aud rename column assay_name to name;
alter table assay_aud rename column assay_type to type;
rename assay_seq to assay_sequence;
alter table assay_result rename column assay_result_id to id;
alter table assay_result_aud rename column assay_result_id to id;
rename assay_result_seq to assay_result_sequence;
alter table assay_result_value rename column assay_result_value_id to id;
alter table assay_result_value_aud rename column assay_result_value_id to id;
rename assay_result_value_seq to assay_result_value_sequence;
alter table assay_attribute rename column assay_attribute_id to id;
alter table assay_attribute_aud rename column assay_attribute_id to id;
alter table assay_attribute rename column assay_attribute_name to name;
alter table assay_attribute_aud rename column assay_attribute_name to name;
alter table assay_attribute rename column is_required to required;
alter table assay_attribute_aud rename column is_required to required;
alter table assay_attribute rename column is_output to output;
alter table assay_attribute_aud rename column is_output to output;
rename assay_attribute_seq to assay_attribute_sequence;
alter table study_enclosure rename to enclosure;
alter table study_enclosure_aud rename to enclosure_aud;
alter table biosample rename COLUMN topparent_id to top_parent_id;
alter table biosample_aud rename COLUMN topparent_id to top_parent_id;
alter table sampling rename COLUMN study_sampling_id to namedsampling_id;
alter table stage_assignment rename to assignment;
alter table stage_assignment_aud rename to assignment_aud;
rename stage_assignment_sequence to assignment_sequence;
ALTER TABLE ASSAY_RESULT_VALUE ADD CRE_USER VARCHAR(255);
ALTER TABLE ASSAY_RESULT_VALUE ADD CRE_DATE DATE;
ALTER TABLE ASSAY_RESULT_VALUE_AUD ADD CRE_USER VARCHAR(255);
ALTER TABLE ASSAY_RESULT_VALUE_AUD ADD CRE_DATE DATE;
ALTER TABLE ASSAY_RESULT_VALUE ADD UPD_USER VARCHAR(255);
ALTER TABLE ASSAY_RESULT_VALUE ADD UPD_DATE DATE;
ALTER TABLE ASSAY_RESULT_VALUE_AUD ADD UPD_USER VARCHAR(255);
ALTER TABLE ASSAY_RESULT_VALUE_AUD ADD UPD_DATE DATE;
ALTER TABLE BIOLOCATION_AUD ADD TYPE NUMBER(10,0);
rename planned_sample_seq to planned_sample_sequence;
ALTER TABLE PLANNED_SAMPLE ADD CRE_USER VARCHAR(255);
ALTER TABLE PLANNED_SAMPLE ADD CRE_DATE DATE;
ALTER TABLE PLANNED_SAMPLE_AUD ADD CRE_USER VARCHAR(255);
ALTER TABLE PLANNED_SAMPLE_AUD ADD CRE_DATE DATE;
ALTER TABLE PLANNED_SAMPLE ADD UPD_USER VARCHAR(255);
ALTER TABLE PLANNED_SAMPLE ADD UPD_DATE DATE;
ALTER TABLE PLANNED_SAMPLE_AUD ADD UPD_USER VARCHAR(255);
ALTER TABLE PLANNED_SAMPLE_AUD ADD UPD_DATE DATE;
ALTER TABLE PROPERTY_LINK ADD CRE_USER VARCHAR(255);
ALTER TABLE PROPERTY_LINK ADD CRE_DATE DATE;
ALTER TABLE PROPERTY_LINK_AUD ADD CRE_USER VARCHAR(255);
ALTER TABLE PROPERTY_LINK_AUD ADD CRE_DATE DATE;
ALTER TABLE PROPERTY_LINK ADD UPD_USER VARCHAR(255);
ALTER TABLE PROPERTY_LINK ADD UPD_DATE DATE;
ALTER TABLE PROPERTY_LINK_AUD ADD UPD_USER VARCHAR(255);
ALTER TABLE PROPERTY_LINK_AUD ADD UPD_DATE DATE;
ALTER TABLE DOCUMENT ADD BYTES BLOB;
UPDATE DOCUMENT D SET d.bytes = (select bytes from document_bytes where id = d.document_bytes_id);
ALTER TABLE DOCUMENT DROP COLUMN DOCUMENT_BYTES_ID;
ALTER TABLE DOCUMENT ADD UPDUSER VARCHAR(255);
ALTER TABLE DOCUMENT ADD UPDDATE DATE;
ALTER TABLE DOCUMENT_AUD DROP COLUMN DOCUMENT_BYTES_ID;
ALTER TABLE DOCUMENT_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE DOCUMENT_AUD ADD UPDDATE DATE;
DROP TABLE DOCUMENT_BYTES;
DROP TABLE DOCUMENT_BYTES_AUD;
ALTER TABLE BIOTYPE_METADATA ADD CREUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA ADD CREDATE DATE;
ALTER TABLE BIOTYPE_METADATA_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_AUD ADD CREDATE DATE;
ALTER TABLE BIOTYPE_METADATA ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA ADD UPDDATE DATE;
ALTER TABLE BIOTYPE_METADATA_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_AUD ADD UPDDATE DATE;
ALTER TABLE SAMPLING_PARAMETER ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_PARAMETER ADD CREDATE DATE;
ALTER TABLE SAMPLING_PARAMETER_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_PARAMETER_AUD ADD CREDATE DATE;
ALTER TABLE SAMPLING_PARAMETER ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_PARAMETER ADD UPDDATE DATE;
ALTER TABLE SAMPLING_PARAMETER_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_PARAMETER_AUD ADD UPDDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT ADD CREDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_AUD ADD CREDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT ADD UPDDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_AUD ADD UPDDATE DATE;
alter table assignment rename COLUMN strat to stratification;
alter table assignment_aud rename COLUMN strat to stratification;
ALTER TABLE stage DROP COLUMN offset_From_Study_D0;
ALTER TABLE assay DROP COLUMN type;
ALTER TABLE assay_aud DROP COLUMN type;
ALTER TABLE stage DROP COLUMN duration;
ALTER TABLE stage_aud DROP COLUMN duration;
ALTER TABLE biosample DROP COLUMN status;
ALTER TABLE biosample_aud DROP COLUMN status;
alter table SCHEDULE_PHASE rename column STUDY_SCHEDULE_ID to SCHEDULE_ID;
alter table SCHEDULE_PHASE rename column STUDY_PHASE_ID to PHASE_ID;
alter table SCHEDULE_PHASE_AUD rename column STUDY_SCHEDULE_ID to SCHEDULE_ID;
alter table SCHEDULE_PHASE_AUD  rename column STUDY_PHASE_ID to PHASE_ID;
alter table ASSAY_RESULT_STUDY_ASSIGNMENT rename to RESULT_ASSIGNMENT; 
alter table ASSAY_RESULT_STUDY_ASSIGNMENT_AUD rename to RESULT_ASSIGNMENT_AUD;
rename ASSAY_RESULT_STUDY_ASSIGNMENT_SEQ to RESULT_ASSIGNMENT_SEQ;
ALTER TABLE BIOTYPE DROP COLUMN CATEGORY;
ALTER TABLE BIOTYPE_AUD DROP COLUMN CATEGORY;
alter table BIOTYPE_AUD rename column CAT to CATEGORY;
alter table BIOTYPE rename column CAT to CATEGORY;
alter table GROUP_BIOTYPE_METADATAVALUE rename column STUDY_GROUP_ID to GROUP_ID;
alter table GROUP_BIOTYPE_METADATAVALUE_AUD rename column STUDY_GROUP_ID to GROUP_ID;
alter table STAGE_BIOTYPE_METADATAVALUE rename column STUDY_STAGE_ID to STAGE_ID;
alter table STAGE_BIOTYPE_METADATAVALUE_AUD rename column STUDY_STAGE_ID to STAGE_ID;
alter table SUBGROUP_BIOTYPE_METADATAVALUE rename column STUDY_SUBGROUP_ID to SUBGROUP_ID;
alter table SUBGROUP_BIOTYPE_METADATAVALUE_AUD rename column STUDY_SUBGROUP_ID to SUUBGROUP_ID;
ALTER TABLE assignment_aud DROP COLUMN rev;
ALTER TABLE STUDY_GROUP DROP COLUMN TREATMENTMODEL;
ALTER TABLE STUDY_GROUP_AUD DROP COLUMN TREATMENTMODEL;
ALTER TABLE ASSAY_ATTRIBUTE ADD OUTPUT_TYPE VARCHAR(255);
ALTER TABLE ASSAY_ATTRIBUTE_AUD ADD OUTPUT_TYPE VARCHAR(255);
UPDATE ASSAY_ATTRIBUTE set OUTPUT_TYPE='INPUT' WHERE OUTPUT=0;
UPDATE ASSAY_ATTRIBUTE set OUTPUT_TYPE='OUTPUT' WHERE OUTPUT=1;
UPDATE ASSAY_ATTRIBUTE set OUTPUT_TYPE='INFO' WHERE OUTPUT=2;
ALTER TABLE ASSAY_ATTRIBUTE DROP COLUMN OUTPUT;
ALTER TABLE ASSAY_ATTRIBUTE_AUD DROP COLUMN OUTPUT;
ALTER TABLE BIOSAMPLE_ENCLOSURE DROP COLUMN IN_DATE;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP COLUMN IN_DATE;
ALTER TABLE BIOSAMPLE_ENCLOSURE DROP COLUMN OUT_DATE;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP COLUMN OUT_DATE;
ALTER TABLE BIOSAMPLE DROP COLUMN ATTACHEDSTUDY_ID;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN ATTACHEDSTUDY_ID;
ALTER TABLE BIOSAMPLE DROP COLUMN CONTAINER_ID;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN CONTAINER_ID;
DROP VIEW EMPLOYEE;
DROP VIEW EMPLOYEE_AUD;
DROP VIEW EMPLOYEE_GROUP;
DROP VIEW EMPLOYEE_GROUP_AUD;
DROP VIEW EMPLOYEE_GROUP_LINK;
DROP VIEW EMPLOYEE_GROUP_LINK_AUD;
ALTER TABLE LOGENTRY DROP COLUMN ID;
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD PRIMARY KEY (BIOSAMPLE_ID, LINKEDBIOSAMPLE_ID, BIOTYPEMETADATA_ID);
ALTER TABLE BIOSAMPLE_BIOSAMPLE RENAME COLUMN LINKEDBIOSAMPLE_ID to LINKED_BIOSAMPLE_ID;
ALTER TABLE biolocation DROP COLUMN containertype;
ALTER TABLE biolocation_aud DROP COLUMN containertype;
ALTER TABLE biolocation DROP COLUMN type;
ALTER TABLE biolocation_aud DROP COLUMN type;
ALTER TABLE administration DROP COLUMN weight_string;
ALTER TABLE administration_aud DROP COLUMN weight_string;
ALTER TABLE STUDY DROP COLUMN LICENCENO;
ALTER TABLE STUDY_aud DROP COLUMN LICENCENO;
alter table BIOSAMPLE_BIOSAMPLE_AUD rename column LINKEDBIOSAMPLE_ID to LINKED_BIOSAMPLE_ID;

ALTER TABLE STAGE_BIOTYPE_METADATAVALUE RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE_AUD RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE_AUD RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE_AUD RENAME COLUMN BIOTYPE_METADATAVALUE_ID TO BIOTYPE_METADATA_VALUE_ID;

ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD CREUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD CREDATE DATE;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD ADD CREDATE DATE;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD UPDDATE DATE;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD ADD UPDDATE DATE;

ALTER TABLE ENCLOSURE ADD CREUSER VARCHAR(255);
ALTER TABLE ENCLOSURE ADD CREDATE DATE;
ALTER TABLE ENCLOSURE_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE ENCLOSURE_AUD ADD CREDATE DATE;
ALTER TABLE ENCLOSURE ADD UPDUSER VARCHAR(255);
ALTER TABLE ENCLOSURE ADD UPDDATE DATE;
ALTER TABLE ENCLOSURE_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE ENCLOSURE_AUD ADD UPDDATE DATE;

ALTER TABLE STUDY_GROUP ADD CREUSER VARCHAR(255);
ALTER TABLE STUDY_GROUP ADD CREDATE DATE;
ALTER TABLE STUDY_GROUP_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE STUDY_GROUP_AUD ADD CREDATE DATE;
ALTER TABLE STUDY_GROUP ADD UPDUSER VARCHAR(255);
ALTER TABLE STUDY_GROUP ADD UPDDATE DATE;
ALTER TABLE STUDY_GROUP_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE STUDY_GROUP_AUD ADD UPDDATE DATE;

ALTER TABLE BIOSAMPLE_DOCUMENT ADD CREUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_DOCUMENT ADD CREDATE DATE;
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD ADD CREDATE DATE;
ALTER TABLE BIOSAMPLE_DOCUMENT ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_DOCUMENT ADD UPDDATE DATE;
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD ADD UPDDATE DATE;

ALTER TABLE SAMPLING ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING ADD CREDATE DATE;
ALTER TABLE SAMPLING_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_AUD ADD CREDATE DATE;
ALTER TABLE SAMPLING ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING ADD UPDDATE DATE;
ALTER TABLE SAMPLING_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_AUD ADD UPDDATE DATE;

ALTER TABLE STUDY_DOCUMENT ADD CREUSER VARCHAR(255);
ALTER TABLE STUDY_DOCUMENT ADD CREDATE DATE;
ALTER TABLE STUDY_DOCUMENT_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE STUDY_DOCUMENT_AUD ADD CREDATE DATE;
ALTER TABLE STUDY_DOCUMENT ADD UPDUSER VARCHAR(255);
ALTER TABLE STUDY_DOCUMENT ADD UPDDATE DATE;
ALTER TABLE STUDY_DOCUMENT_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE STUDY_DOCUMENT_AUD ADD UPDDATE DATE;

ALTER TABLE ASSAY_ATTRIBUTE ADD CREUSER VARCHAR(255);
ALTER TABLE ASSAY_ATTRIBUTE ADD CREDATE DATE;
ALTER TABLE ASSAY_ATTRIBUTE_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE ASSAY_ATTRIBUTE_AUD ADD CREDATE DATE;
ALTER TABLE ASSAY_ATTRIBUTE ADD UPDUSER VARCHAR(255);
ALTER TABLE ASSAY_ATTRIBUTE ADD UPDDATE DATE;
ALTER TABLE ASSAY_ATTRIBUTE_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE ASSAY_ATTRIBUTE_AUD ADD UPDDATE DATE;

ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD CREUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD CREDATE DATE;
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD ADD CREDATE DATE;
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD UPDDATE DATE;
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD ADD UPDDATE DATE;

/**GROUP_BIOTYPE_METADATAVALUE**/
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE ADD ID NUMBER(19,0);
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE_AUD ADD ID NUMBER(19,0);
--PUT ID COL ON 1st POSITION
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE MODIFY (
  	BIOTYPE_METADATAVALUE_ID invisible,
	CREDATE invisible,
	CREUSER invisible,
	GROUP_ID invisible,
	UPDDATE invisible,
	UPDUSER invisible
);
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE MODIFY (
  	BIOTYPE_METADATAVALUE_ID visible,
	CREDATE visible,
	CREUSER visible,
	GROUP_ID visible,
	UPDDATE visible,
	UPDUSER visible
);
CREATE SEQUENCE GROUP_BIOTYPE_METADATAVALUE_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON GROUP_BIOTYPE_METADATAVALUE_SEQ TO SPIRIT_FATCLIENT;
update GROUP_BIOTYPE_METADATAVALUE set id = GROUP_BIOTYPE_METADATAVALUE_SEQ.nextval;
--ALTER TABLE GROUP_BIOTYPE_METADATAVALUE drop column id;
--ALTER SEQUENCE GROUP_BIOTYPE_METADATAVALUE_SEQ RESTART START WITH 1;

/**STAGE_BIOTYPE_METADATAVALUE**/
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE ADD ID NUMBER(19,0);
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE_AUD ADD ID NUMBER(19,0);
--PUT ID COL ON 1st POSITION
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE MODIFY (
    BIOTYPE_METADATAVALUE_ID invisible,
    CREDATE invisible,
    CREUSER invisible,
    STAGE_ID invisible,
    UPDDATE invisible,
    UPDUSER invisible
);
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE MODIFY (
    BIOTYPE_METADATAVALUE_ID visible,
    CREDATE visible,
    CREUSER visible,
    STAGE_ID visible,
    UPDDATE visible,
    UPDUSER visible
);
CREATE SEQUENCE STAGE_BIOTYPE_METADATAVALUE_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON STAGE_BIOTYPE_METADATAVALUE_SEQ TO SPIRIT_FATCLIENT;
UPDATE STAGE_BIOTYPE_METADATAVALUE SET ID = STAGE_BIOTYPE_METADATAVALUE_SEQ.nextval;
--ALTER TABLE STAGE_BIOTYPE_METADATAVALUE drop column id;
--ALTER SEQUENCE STAGE_BIOTYPE_METADATAVALUE_SEQ RESTART START WITH 1;

/**SUBGROUP_BIOTYPE_METADATAVALUE**/
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE ADD ID NUMBER(19,0);
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE_AUD ADD ID NUMBER(19,0);
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE_AUD rename column SUUBGROUP_ID to SUBGROUP_ID;
--PUT ID COL ON 1st POSITION
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE MODIFY (
    BIOTYPE_METADATAVALUE_ID invisible,
    CREDATE invisible,
    CREUSER invisible,
    SUBGROUP_ID invisible,
    UPDDATE invisible,
    UPDUSER invisible
);
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE MODIFY (
    BIOTYPE_METADATAVALUE_ID visible,
    CREDATE visible,
    CREUSER visible,
    SUBGROUP_ID visible,
    UPDDATE visible,
    UPDUSER visible
);
CREATE SEQUENCE SUBGROUP_BIOTYPE_METADATAVALUE_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON SUBGROUP_BIOTYPE_METADATAVALUE_SEQ TO SPIRIT_FATCLIENT;
UPDATE SUBGROUP_BIOTYPE_METADATAVALUE SET ID = SUBGROUP_BIOTYPE_METADATAVALUE_SEQ.nextval;
--ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE drop column id;
--ALTER SEQUENCE SUBGROUP_BIOTYPE_METADATAVALUE_SEQ RESTART START WITH 1;

/**STUDY_DOCUMENT**/
ALTER TABLE STUDY_DOCUMENT ADD ID NUMBER(19,0);
ALTER TABLE STUDY_DOCUMENT_AUD ADD ID NUMBER(19,0);
--PUT ID COL ON 1st POSITION
ALTER TABLE STUDY_DOCUMENT MODIFY (
    DOCUMENTS_ID invisible,
    STUDY_ID invisible
);
ALTER TABLE STUDY_DOCUMENT MODIFY (
    DOCUMENTS_ID visible,
    STUDY_ID visible
);
CREATE SEQUENCE STUDY_DOCUMENT_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 556 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON STUDY_DOCUMENT_SEQ TO SPIRIT_FATCLIENT;
UPDATE STUDY_DOCUMENT SET ID = STUDY_DOCUMENT_SEQ.nextval;
--ALTER TABLE STUDY_DOCUMENT drop column id;
--ALTER SEQUENCE STUDY_DOCUMENT_SEQ RESTART START WITH 1;

/**BIOSAMPLE_DOCUMENT**/
ALTER TABLE BIOSAMPLE_DOCUMENT ADD ID NUMBER(19,0);
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD ADD ID NUMBER(19,0);
--PUT ID COL ON 1st POSITION
ALTER TABLE BIOSAMPLE_DOCUMENT MODIFY (
    BIOSAMPLE_ID invisible,
    BIOTYPEMETADATA_ID invisible,
    LINKEDDOCUMENT_ID invisible
);
ALTER TABLE BIOSAMPLE_DOCUMENT MODIFY (
    BIOSAMPLE_ID visible,
    BIOTYPEMETADATA_ID visible,
    LINKEDDOCUMENT_ID visible
);
CREATE SEQUENCE BIOSAMPLE_DOCUMENT_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON BIOSAMPLE_DOCUMENT_SEQ TO SPIRIT_FATCLIENT;
UPDATE BIOSAMPLE_DOCUMENT SET ID = BIOSAMPLE_DOCUMENT_SEQ.nextval;
--ALTER TABLE BIOSAMPLE_DOCUMENT drop column id;
--ALTER SEQUENCE BIOSAMPLE_DOCUMENT_SEQ RESTART START WITH 1;

/**BIOSAMPLE_BIOSAMPLE**/
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD ID NUMBER(19,0);
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD ADD ID NUMBER(19,0);
ALTER TABLE BIOSAMPLE_BIOSAMPLE MODIFY (
    BIOSAMPLE_ID invisible,
    BIOTYPEMETADATA_ID invisible,
    LINKED_BIOSAMPLE_ID invisible
);
ALTER TABLE BIOSAMPLE_BIOSAMPLE MODIFY (
    BIOSAMPLE_ID visible,
    BIOTYPEMETADATA_ID visible,
    LINKED_BIOSAMPLE_ID visible
);
CREATE SEQUENCE BIOSAMPLE_BIOSAMPLE_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
GRANT SELECT ON BIOSAMPLE_BIOSAMPLE_SEQ TO SPIRIT_FATCLIENT;
UPDATE BIOSAMPLE_BIOSAMPLE SET ID = BIOSAMPLE_BIOSAMPLE_SEQ.nextval;
--ALTER TABLE BIOSAMPLE_BIOSAMPLE drop column id;
--ALTER SEQUENCE BIOSAMPLE_BIOSAMPLE_SEQ RESTART START WITH 1;

ALTER TABLE ADMINISTRATION MODIFY (NAMED_TREATMENT_ID NOT NULL);

ALTER TABLE BIOSAMPLE_AUD DROP COLUMN CONTAINERINDEX;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN CONTAINER_TYPE;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN ALIQUOT_TODEL;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN ATTACHEDSUBGROUP;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN GROUP_ID;

ALTER TABLE FOOD_WATER_AUD DROP COLUMN LOCATION_ID;

ALTER TABLE PHASE_AUD DROP COLUMN FULLNAME_TODEL;
ALTER TABLE PHASE_AUD DROP COLUMN LICENCENO_TODEL;
ALTER TABLE PHASE_AUD DROP COLUMN RND_DATA_TODEL;
ALTER TABLE PHASE_AUD DROP COLUMN RND_EXPERIMENTER_TODEL;
ALTER TABLE PHASE_AUD DROP COLUMN RND_MAXANIMALS_TODEL;
ALTER TABLE PHASE_AUD DROP COLUMN RND_NUMBERING_TODEL;

--CONSTRAINTS AUD TABLES
ALTER TABLE ACTIONPATTERNS_AUD DROP CONSTRAINT SYS_C0041440;
ALTER TABLE ACTIONPATTERNS_AUD DROP CONSTRAINT SYS_C0041440;
ALTER TABLE ACTIONPATTERNS_AUD DROP CONSTRAINT SYS_C0041441;

ALTER TABLE ADMINISTRATION_AUD DROP CONSTRAINT SYS_C0041498;
ALTER TABLE ADMINISTRATION_AUD DROP CONSTRAINT SYS_C0041499;

ALTER TABLE ASSAY_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0041079;
ALTER TABLE ASSAY_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0041080;
ALTER TABLE ASSAY_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0041230;
ALTER TABLE ASSAY_ATTRIBUTE_AUD DROP CONSTRAINT FKE3541B47DF74E053;

ALTER TABLE ASSAY_AUD DROP CONSTRAINT FK47DDAFEADF74E053;
ALTER TABLE ASSAY_AUD DROP CONSTRAINT SYS_C0041053;
ALTER TABLE ASSAY_AUD DROP CONSTRAINT SYS_C0041054;
ALTER TABLE ASSAY_AUD DROP CONSTRAINT SYS_C0041221;

ALTER TABLE ASSAY_RESULT_AUD DROP CONSTRAINT SYS_C0041129;
ALTER TABLE ASSAY_RESULT_AUD DROP CONSTRAINT SYS_C0041130;
ALTER TABLE ASSAY_RESULT_AUD DROP CONSTRAINT SYS_C0041247;
ALTER TABLE ASSAY_RESULT_AUD DROP CONSTRAINT FK6DE17114DF74E053;

ALTER TABLE ASSAY_RESULT_VALUE_AUD DROP CONSTRAINT SYS_C0041195;
ALTER TABLE ASSAY_RESULT_VALUE_AUD DROP CONSTRAINT SYS_C0041196;
ALTER TABLE ASSAY_RESULT_VALUE_AUD DROP CONSTRAINT SYS_C0041271;
ALTER TABLE ASSAY_RESULT_VALUE_AUD DROP CONSTRAINT FK3DFB646DF74E053;

ALTER TABLE ASSIGNMENT_PATTERN_AUD DROP CONSTRAINT SYS_C0047239;

ALTER TABLE BIOLOCATION_AUD DROP CONSTRAINT SYS_C0041088;
ALTER TABLE BIOLOCATION_AUD DROP CONSTRAINT SYS_C0041089;
ALTER TABLE BIOLOCATION_AUD DROP CONSTRAINT SYS_C0041233;
ALTER TABLE BIOLOCATION_AUD DROP CONSTRAINT FKB3F7BFEEDF74E053;

ALTER TABLE BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041169;
ALTER TABLE BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041170;
ALTER TABLE BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041261;
ALTER TABLE BIOSAMPLE_AUD DROP CONSTRAINT FKC788B163DF74E053;

ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041131;
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041132;
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0041133;
ALTER TABLE BIOSAMPLE_BIOSAMPLE_AUD DROP CONSTRAINT BIOSAMPLE_BIOSAMPLE_AUD_FK1;

ALTER TABLE BIOSAMPLE_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041163;
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041164;
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041165;
ALTER TABLE BIOSAMPLE_DOCUMENT_AUD DROP CONSTRAINT BIOSAMPLE_DOCUMENT_AUD_FK1;

ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041115;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041116;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041117;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041118;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041119;
ALTER TABLE BIOSAMPLE_ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041322;

ALTER TABLE BIOTYPE_AUD DROP CONSTRAINT SYS_C0041142;
ALTER TABLE BIOTYPE_AUD DROP CONSTRAINT SYS_C0041143;
ALTER TABLE BIOTYPE_AUD DROP CONSTRAINT SYS_C0041255;
ALTER TABLE BIOTYPE_AUD DROP CONSTRAINT SYS_C0041340;

ALTER TABLE BIOTYPE_METADATA_AUD DROP CONSTRAINT SYS_C0041125;
ALTER TABLE BIOTYPE_METADATA_AUD DROP CONSTRAINT SYS_C0041126;
ALTER TABLE BIOTYPE_METADATA_AUD DROP CONSTRAINT SYS_C0041246;
ALTER TABLE BIOTYPE_METADATA_AUD DROP CONSTRAINT SYS_C0041324;

ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0049267;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0049268;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0049269;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0049270;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE_AUD DROP CONSTRAINT SYS_C0049271;

ALTER TABLE BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041386;
ALTER TABLE BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041387;
ALTER TABLE BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041388;

ALTER TABLE DOCUMENT_AUD DROP CONSTRAINT SYS_C0041127;
ALTER TABLE DOCUMENT_AUD DROP CONSTRAINT SYS_C0041128;
ALTER TABLE DOCUMENT_AUD DROP CONSTRAINT SYS_C0041325;

ALTER TABLE ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041084;
ALTER TABLE ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041085;
ALTER TABLE ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041086;
ALTER TABLE ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041087;
ALTER TABLE ENCLOSURE_AUD DROP CONSTRAINT SYS_C0041303;

ALTER TABLE EXECUTION_DETAILS_AUD DROP CONSTRAINT SYS_C0041491;
ALTER TABLE EXECUTION_DETAILS_AUD DROP CONSTRAINT SYS_C0041492;

ALTER TABLE FOOD_WATER_AUD DROP CONSTRAINT SYS_C0041059;
ALTER TABLE FOOD_WATER_AUD DROP CONSTRAINT SYS_C0041060;
ALTER TABLE FOOD_WATER_AUD DROP CONSTRAINT SYS_C0041224;
ALTER TABLE FOOD_WATER_AUD DROP CONSTRAINT FK8A4E48A7DF74E053;

ALTER TABLE GROUP_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041462;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041463;

ALTER TABLE GROUP_PATTERN_AUD DROP CONSTRAINT SYS_C0041452;
ALTER TABLE GROUP_PATTERN_AUD DROP CONSTRAINT SYS_C0041453;

ALTER TABLE NAMEDSAMPLING_AUD DROP CONSTRAINT SYS_C0041209;
ALTER TABLE NAMEDSAMPLING_AUD DROP CONSTRAINT SYS_C0041210;
ALTER TABLE NAMEDSAMPLING_AUD DROP CONSTRAINT SYS_C0041279;
ALTER TABLE NAMEDSAMPLING_AUD DROP CONSTRAINT FK914D310EDF74E053;

ALTER TABLE NAMEDTREATMENT_AUD DROP CONSTRAINT SYS_C0041479;
ALTER TABLE NAMEDTREATMENT_AUD DROP CONSTRAINT SYS_C0041480;

ALTER TABLE PHASE_AUD DROP CONSTRAINT SYS_C0041213;
ALTER TABLE PHASE_AUD DROP CONSTRAINT SYS_C0041214;
ALTER TABLE PHASE_AUD DROP CONSTRAINT SYS_C0041278;
ALTER TABLE PHASE_AUD DROP CONSTRAINT FK7324EA96DF74E053;

ALTER TABLE PLANNED_SAMPLE_AUD DROP CONSTRAINT SYS_C0041502;
ALTER TABLE PLANNED_SAMPLE_AUD DROP CONSTRAINT SYS_C0041503;

ALTER TABLE PROPERTY_AUD DROP CONSTRAINT SYS_C0049250;
ALTER TABLE PROPERTY_AUD DROP CONSTRAINT SYS_C0049251;
ALTER TABLE PROPERTY_AUD DROP CONSTRAINT SYS_C0049252;
ALTER TABLE PROPERTY_AUD DROP CONSTRAINT SYS_C0049253;

ALTER TABLE RESULT_ASSIGNMENT_AUD DROP CONSTRAINT SYS_C0041485;
ALTER TABLE RESULT_ASSIGNMENT_AUD DROP CONSTRAINT SYS_C0041486;

ALTER TABLE SAMPLING_AUD DROP CONSTRAINT SYS_C0041184;
ALTER TABLE SAMPLING_AUD DROP CONSTRAINT SYS_C0041185;
ALTER TABLE SAMPLING_AUD DROP CONSTRAINT SYS_C0041266;
ALTER TABLE SAMPLING_AUD DROP CONSTRAINT FK91D2A238DF74E053;

ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0049294;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0049295;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0049296;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0049297;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD DROP CONSTRAINT SYS_C0049298;

ALTER TABLE SAMPLING_MEASUREMENT_AUD DROP CONSTRAINT SYS_C0049285;
ALTER TABLE SAMPLING_MEASUREMENT_AUD DROP CONSTRAINT SYS_C0049286;
ALTER TABLE SAMPLING_MEASUREMENT_AUD DROP CONSTRAINT SYS_C0049287;
ALTER TABLE SAMPLING_MEASUREMENT_AUD DROP CONSTRAINT SYS_C0049288;
ALTER TABLE SAMPLING_MEASUREMENT_AUD DROP CONSTRAINT SYS_C0049289;

ALTER TABLE SAMPLING_PARAMETER_AUD DROP CONSTRAINT SYS_C0049276;
ALTER TABLE SAMPLING_PARAMETER_AUD DROP CONSTRAINT SYS_C0049277;
ALTER TABLE SAMPLING_PARAMETER_AUD DROP CONSTRAINT SYS_C0049278;
ALTER TABLE SAMPLING_PARAMETER_AUD DROP CONSTRAINT SYS_C0049279;
ALTER TABLE SAMPLING_PARAMETER_AUD DROP CONSTRAINT SYS_C0049280;

ALTER TABLE SCHEDULE_AUD DROP CONSTRAINT SYS_C0041423;
ALTER TABLE SCHEDULE_AUD DROP CONSTRAINT SYS_C0041424;

ALTER TABLE SCHEDULE_PHASE_AUD DROP CONSTRAINT SYS_C0041431;
ALTER TABLE SCHEDULE_PHASE_AUD DROP CONSTRAINT SYS_C0041432;

ALTER TABLE SPIRIT_PROPERTY_AUD DROP CONSTRAINT SYS_C0041055;
ALTER TABLE SPIRIT_PROPERTY_AUD DROP CONSTRAINT SYS_C0041056;
ALTER TABLE SPIRIT_PROPERTY_AUD DROP CONSTRAINT SYS_C0041222;
ALTER TABLE SPIRIT_PROPERTY_AUD DROP CONSTRAINT SPIRIT_PROPERTY_AUD_FK;

ALTER TABLE STAGE_AUD DROP CONSTRAINT SYS_C0041408;
ALTER TABLE STAGE_AUD DROP CONSTRAINT SYS_C0041410;

ALTER TABLE STAGE_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041472;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041473;

ALTER TABLE STAGE_PATTERN_AUD DROP CONSTRAINT SYS_C0041446;
ALTER TABLE STAGE_PATTERN_AUD DROP CONSTRAINT SYS_C0041447;

ALTER TABLE STUDY_AUD DROP CONSTRAINT SYS_C0041057;
ALTER TABLE STUDY_AUD DROP CONSTRAINT SYS_C0041058;
ALTER TABLE STUDY_AUD DROP CONSTRAINT SYS_C0041223;
ALTER TABLE STUDY_AUD DROP CONSTRAINT FK31A046FADF74E053;

ALTER TABLE STUDY_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041073;
ALTER TABLE STUDY_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041074;
ALTER TABLE STUDY_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041075;
ALTER TABLE STUDY_DOCUMENT_AUD DROP CONSTRAINT SYS_C0041229;
ALTER TABLE STUDY_DOCUMENT_AUD DROP CONSTRAINT FK31DD7842DF74E053;

ALTER TABLE STUDY_GROUP_AUD DROP CONSTRAINT SYS_C0041065;
ALTER TABLE STUDY_GROUP_AUD DROP CONSTRAINT SYS_C0041066;
ALTER TABLE STUDY_GROUP_AUD DROP CONSTRAINT SYS_C0041225;
ALTER TABLE STUDY_GROUP_AUD DROP CONSTRAINT FK3424B59ADF74E053;

ALTER TABLE PROPERTY_LINK_AUD DROP CONSTRAINT SYS_C0049258;
ALTER TABLE PROPERTY_LINK_AUD DROP CONSTRAINT SYS_C0049259;
ALTER TABLE PROPERTY_LINK_AUD DROP CONSTRAINT SYS_C0049260;
ALTER TABLE PROPERTY_LINK_AUD DROP CONSTRAINT SYS_C0049261;
ALTER TABLE PROPERTY_LINK_AUD DROP CONSTRAINT SYS_C0049262;

ALTER TABLE SUBGROUP_AUD DROP CONSTRAINT SYS_C0041397;
ALTER TABLE SUBGROUP_AUD DROP CONSTRAINT SYS_C0041398;

ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041467;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE_AUD DROP CONSTRAINT SYS_C0041468;

ALTER TABLE SUBGROUP_PATTERN_AUD DROP CONSTRAINT SYS_C0041458;
ALTER TABLE SUBGROUP_PATTERN_AUD DROP CONSTRAINT SYS_C0041459;

ALTER TABLE PHASE DROP COLUMN RND_ALLSAMPLES;
ALTER TABLE PHASE_AUD DROP COLUMN RND_ALLSAMPLES;
ALTER TABLE BIOSAMPLE DROP COLUMN INHERITEDGROUP_ID;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN INHERITEDGROUP_ID;
ALTER TABLE BIOSAMPLE DROP COLUMN INHERITEDSUBGROUP;
ALTER TABLE BIOSAMPLE_AUD DROP COLUMN INHERITEDSUBGROUP;
ALTER TABLE NAMEDTREATMENT DROP COLUMN NAMED_TREATMENT_ID;
ALTER TABLE NAMEDTREATMENT_AUD DROP COLUMN NAMED_TREATMENT_ID;

DROP TABLE study_treatment;
DROP TABLE study_treatment_aud;

alter table SAMPLING_MEASUREMENT_ATTRIBUTE rename COLUMN TESTATTRIBUTE_ID to ASSAY_ATTRIBUTE_ID;
alter table SAMPLING_MEASUREMENT_ATTRIBUTE_AUD rename COLUMN TESTATTRIBUTE_ID to ASSAY_ATTRIBUTE_ID;
alter table SAMPLING_MEASUREMENT rename COLUMN TEST_ID to ASSAY_ID;
alter table SAMPLING_MEASUREMENT_AUD rename COLUMN TEST_ID to ASSAY_ID;

ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE  ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE  ADD CREDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD ADD CREUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD ADD CREDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE ADD UPDDATE DATE;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD ADD UPDUSER VARCHAR(255);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE_AUD ADD UPDDATE DATE;

DELETE from PLANNED_SAMPLE ps where (select count(*) from STAGE where id=ps.STAGE_ID)=0;
DELETE from SCHEDULE_PHASE where SCHEDULE_ID in (SELECT id from SCHEDULE s where (SELECT count(*) from ACTIONPATTERNS where SCHEDULE_ID=s.id)=0);
DELETE from SCHEDULE s where (SELECT count(*) from ACTIONPATTERNS where SCHEDULE_ID=s.id)=0;
DELETE from BIOTYPE_METADATA_BIOSAMPLE s where (SELECT count(*) from BIOTYPE_METADATA_BIOSAMPLE, BIOSAMPLE b where s.BIOSAMPLE_ID=b.id)=0;
DELETE from PLANNED_SAMPLE s where (SELECT count(*) from PLANNED_SAMPLE, BIOSAMPLE b where s.BIOSAMPLE_ID=b.id)=0;
DELETE from PROPERTY_LINK s where (SELECT count(*) from PROPERTY_LINK, STUDY b where s.STUDY_ID=b.id)=0;

ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD CONSTRAINT FK_BIOTYPE_METADATA_BIOSAMPLE_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID);
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD CONSTRAINT FK_BIOTYPE_METADATA_BIOSAMPLE_METADATA_ID FOREIGN KEY (METADATA_ID) REFERENCES BIOTYPE_METADATA(ID);
ALTER TABLE PLANNED_SAMPLE ADD CONSTRAINT FK_PLANNED_SAMPLE_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID);
ALTER TABLE PLANNED_SAMPLE ADD CONSTRAINT FK_PLANNED_SAMPLE_STAGE_ID FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID);
ALTER TABLE PROPERTY_LINK ADD CONSTRAINT FK_PROPERTY_LINK_PROPERTY_ID FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(ID);
ALTER TABLE PROPERTY_LINK ADD CONSTRAINT FK_PROPERTY_LINK_STUDY_ID FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID);
ALTER TABLE SAMPLING_MEASUREMENT ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_SAMPLING_ID FOREIGN KEY (SAMPLING_ID) REFERENCES SAMPLING(ID);
ALTER TABLE SAMPLING_MEASUREMENT ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_ASSAY_ID FOREIGN KEY (ASSAY_ID) REFERENCES ASSAY(ID);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_ATTRIBUTE_SAMPLING_MEASUREMENT_ID FOREIGN KEY (SAMPLING_MEASUREMENT_ID) REFERENCES SAMPLING_MEASUREMENT(ID);
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_ATTRIBUTE_ASSAY_ATTRIBUTE_ID FOREIGN KEY (ASSAY_ATTRIBUTE_ID) REFERENCES ASSAY_ATTRIBUTE(ID);
ALTER TABLE SAMPLING_PARAMETER ADD CONSTRAINT FK_SAMPLING_PARAMETER_SAMPLING_ID FOREIGN KEY (SAMPLING_ID) REFERENCES SAMPLING(ID);
ALTER TABLE SAMPLING_PARAMETER ADD CONSTRAINT FK_SAMPLING_PARAMETER_BIOTYPEMETADATA_ID FOREIGN KEY (BIOTYPEMETADATA_ID) REFERENCES BIOTYPE_METADATA(ID);

ALTER TABLE SAMPLING DROP COLUMN PARAMETERS;
ALTER TABLE SAMPLING DROP COLUMN EXTRAMEASUREMENT;

REMOVE AUTO ID ASSIGNMENT_PATTERN;

ALTER TABLE ASSIGNMENT_PATTERN ADD CREUSER VARCHAR(255);
ALTER TABLE ASSIGNMENT_PATTERN ADD CREDATE DATE;
ALTER TABLE ASSIGNMENT_PATTERN ADD UPDUSER VARCHAR(255);
ALTER TABLE ASSIGNMENT_PATTERN ADD UPDDATE DATE;

UPDATE NAMEDSAMPLING SET COLOR = 1 WHERE COLOR IS NULL;
ALTER TABLE NAMEDSAMPLING modify COLOR NUMBER NOT NULL;

ALTER TABLE ASSIGNMENT RENAME CONSTRAINT STAGE_ASSIGNMENT_FK_BIOSAMPLE to ASSIGNMENT_FK_BIOSAMPLE;
ALTER TABLE ASSIGNMENT RENAME CONSTRAINT STAGE_ASSIGNMENT_FK_STAGE to ASSIGNMENT_FK_STAGE;
ALTER TABLE ASSIGNMENT RENAME CONSTRAINT STAGE_ASSIGNMENT_FK_SUBGROUP to ASSIGNMENT_FK_SUBGROUP;
ALTER TABLE ASSIGNMENT RENAME CONSTRAINT STAGE_ASSIGNMENT_PK to ASSIGNMENT_PK;


ALTER TABLE STAGE_PATTERN DROP CONSTRAINT STAGE_PATTERN_FK_ACTIONPATTERN;
ALTER TABLE STAGE_PATTERN ADD CONSTRAINT STAGE_PATTERN_FK_ACTIONPATTERN FOREIGN KEY (ACTIONPATTERN_ID) REFERENCES ACTIONPATTERNS(ID) ON DELETE CASCADE;
ALTER TABLE GROUP_PATTERN DROP CONSTRAINT GROUP_PATTERN_FK_ACTIONPATTERN;
ALTER TABLE GROUP_PATTERN ADD CONSTRAINT GROUP_PATTERN_FK_ACTIONPATTERN FOREIGN KEY (ACTIONPATTERN_ID) REFERENCES ACTIONPATTERNS(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP_PATTERN DROP CONSTRAINT SUBGROUP_PATTERN_FK_ACTIONPATTERN;
ALTER TABLE SUBGROUP_PATTERN ADD CONSTRAINT SUBGROUP_PATTERN_FK_ACTIONPATTERN FOREIGN KEY (ACTIONPATTERN_ID) REFERENCES ACTIONPATTERNS(ID) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENT_PATTERN DROP CONSTRAINT ASSIGNMET_PATTERN_FK2;
ALTER TABLE ASSIGNMENT_PATTERN ADD CONSTRAINT ASSIGNMENT_PATTERN_FK_ACTIONPATTERN FOREIGN KEY (PATTERN_ID) REFERENCES ACTIONPATTERNS(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT_VALUE DROP CONSTRAINT FK7C687ED5A2A2E84F;
ALTER TABLE ASSAY_RESULT_VALUE ADD CONSTRAINT ASSAY_RESULT_VALUE_FK_ASSAY_ATTRIBUTE FOREIGN KEY (ASSAY_ATTRIBUTE_ID) REFERENCES ASSAY_ATTRIBUTE(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT_VALUE DROP CONSTRAINT FK7C687ED5D087C0F3;
ALTER TABLE ASSAY_RESULT_VALUE ADD CONSTRAINT ASSAY_RESULT_VALUE_FK_ASSAY_RESULT FOREIGN KEY (ASSAY_RESULT_ID) REFERENCES ASSAY_RESULT(ID) ON DELETE CASCADE;
ALTER TABLE RESULT_ASSIGNMENT DROP CONSTRAINT ASSAY_RESULT_STUDY_ASSIGNMENT_FK_ASSAY_RESULT;
ALTER TABLE RESULT_ASSIGNMENT ADD CONSTRAINT ASSAY_RESULT_STUDY_ASSIGNMENT_FK_ASSAY_RESULT FOREIGN KEY (ASSAY_RESULT_ID) REFERENCES ASSAY_RESULT(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_ATTRIBUTE DROP CONSTRAINT FK9A118C561412E792;
ALTER TABLE ASSAY_ATTRIBUTE ADD CONSTRAINT ASSAY_ATTRIBUTE_FK_ASSAY FOREIGN KEY (ASSAY_ID) REFERENCES ASSAY(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT DROP CONSTRAINT FK3B23D0A31412E792;
ALTER TABLE ASSAY_RESULT ADD CONSTRAINT ASSAY_RESULT_FK_ASSAY FOREIGN KEY (ASSAY_ID) REFERENCES ASSAY(ID) ON DELETE CASCADE;
ALTER TABLE EXECUTION_DETAILS DROP CONSTRAINT EXECUTION_DETAILS_FK_ASSIGNMENT;
ALTER TABLE EXECUTION_DETAILS ADD CONSTRAINT EXECUTION_DETAILS_FK_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ID) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENT_PATTERN DROP CONSTRAINT ASSIGNMET_PATTERN_FK1;
ALTER TABLE ASSIGNMENT_PATTERN ADD CONSTRAINT ASSIGNMET_PATTERN_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ID) ON DELETE CASCADE;
ALTER TABLE RESULT_ASSIGNMENT DROP CONSTRAINT ASSAY_RESULT_STUDY_ASSIGNMENT_FK_ASSIGNMENT;
ALTER TABLE RESULT_ASSIGNMENT ADD CONSTRAINT ASSAY_RESULT_STUDY_ASSIGNMENT_FK_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ID) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENT DROP CONSTRAINT STAGE_ASSIGNMENT_FK_BIOSAMPLE;
ALTER TABLE ASSIGNMENT ADD CONSTRAINT ASSIGNMENT_FK_BIOSAMPLE FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE SET NULL;
ALTER TABLE ASSAY_RESULT DROP CONSTRAINT FK3B23D0A39D08A32C;
ALTER TABLE ASSAY_RESULT ADD CONSTRAINT ASSAY_RESULT_FK_BIOSAMPLE FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE ADMINISTRATION DROP CONSTRAINT ADMINISTRATION_FK_BIOSAMPLE;
ALTER TABLE ADMINISTRATION ADD CONSTRAINT ADMINISTRATION_FK_BIOSAMPLE FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE_ENCLOSURE DROP CONSTRAINT BIOSAMPLE_ENCLOSURE_LINK_FK_BIOSAMPLE;
ALTER TABLE BIOSAMPLE_ENCLOSURE ADD CONSTRAINT BIOSAMPLE_ENCLOSURE_LINK_FK_BIOSAMPLE FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE PLANNED_SAMPLE DROP CONSTRAINT FK_PLANNED_SAMPLE_BIOSAMPLE_ID;
ALTER TABLE PLANNED_SAMPLE ADD CONSTRAINT PLANNED_SAMPLE_FK_PLANNED_SAMPLE_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE DROP CONSTRAINT FK_BIOSAMPLE_ID;
ALTER TABLE BIOTYPE_METADATA_BIOSAMPLE ADD CONSTRAINT BIOTYPE_METADATA_BIOSAMPLE_FK_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE_DOCUMENT DROP CONSTRAINT BIOSAMPLE_DOCUMENT_FK1;
ALTER TABLE BIOSAMPLE_DOCUMENT ADD CONSTRAINT BIOSAMPLE_DOCUMENT_FK_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE_BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_BIOSAMPLE_FK1;
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_BIOSAMPLE_FK_BIOSAMPLE_ID FOREIGN KEY (BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE_BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_BIOSAMPLE_FK2;
ALTER TABLE BIOSAMPLE_BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_BIOSAMPLE_FK_LINKED_BIOSAMPLE_ID FOREIGN KEY (LINKED_BIOSAMPLE_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_PARENT_FK;
ALTER TABLE BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES BIOSAMPLE(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_SUBGROUP_BIOTYPE_METADATAVALUE_FK_METADATAVALUE;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE ADD CONSTRAINT SUBGROUP_BIOTYPE_METADATAVALUE_FK_METADATAVALUE FOREIGN KEY (BIOTYPE_METADATA_VALUE_ID) REFERENCES BIOTYPE_METADATAVALUE(ID) ON DELETE CASCADE;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_GROUP_BIOTYPE_METADATAVALUE_FK_METADATAVALUE;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE ADD CONSTRAINT GROUP_BIOTYPE_METADATAVALUE_FK_METADATAVALUE FOREIGN KEY (BIOTYPE_METADATA_VALUE_ID) REFERENCES BIOTYPE_METADATAVALUE(ID) ON DELETE CASCADE;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_STAGE_BIOTYPE_METADATAVALUE_FK_METADATAVALUE;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE ADD CONSTRAINT STAGE_BIOTYPE_METADATAVALUE_FK_METADATAVALUE FOREIGN KEY (BIOTYPE_METADATA_VALUE_ID) REFERENCES BIOTYPE_METADATAVALUE(ID) ON DELETE CASCADE;
ALTER TABLE STUDY_DOCUMENT DROP CONSTRAINT FKED922AF147ADA1F4;
ALTER TABLE STUDY_DOCUMENT ADD CONSTRAINT STUDY_DOCUMENT_FK_DOCUMENT FOREIGN KEY (DOCUMENTS_ID) REFERENCES DOCUMENT(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE_DOCUMENT DROP CONSTRAINT BIOSAMPLE_DOCUMENT_FK2;
ALTER TABLE BIOSAMPLE_DOCUMENT ADD CONSTRAINT BIOSAMPLE_DOCUMENT_FK_DOCUMENT FOREIGN KEY (LINKEDDOCUMENT_ID) REFERENCES DOCUMENT(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT_VALUE DROP CONSTRAINT ASSAY_RESULT_FK;
ALTER TABLE ASSAY_RESULT_VALUE ADD CONSTRAINT ASSAY_RESULT_VALUE_FK_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(ID) ON DELETE SET NULL;
ALTER TABLE BIOSAMPLE_ENCLOSURE DROP CONSTRAINT BIOSAMPLE_ENCLOSURE_LINK_FK_ENCLOSURE;
ALTER TABLE BIOSAMPLE_ENCLOSURE ADD CONSTRAINT BIOSAMPLE_ENCLOSURE_LINK_FK_ENCLOSURE FOREIGN KEY (ENCLOSURE_ID) REFERENCES ENCLOSURE(ID) ON DELETE CASCADE;
ALTER TABLE FOOD_WATER DROP CONSTRAINT FOOD_WATER_ENCLOSURE_FK;
ALTER TABLE FOOD_WATER ADD CONSTRAINT FOOD_WATER_FK_ENCLOSURE FOREIGN KEY (ENCLOSURE_ID) REFERENCES ENCLOSURE(ID) ON DELETE CASCADE;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_GROUP_BIOTYPE_METADATAVALUE_FK_GROUP;
ALTER TABLE GROUP_BIOTYPE_METADATAVALUE ADD CONSTRAINT GROUP_BIOTYPE_METADATAVALUE_FK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES STUDY_GROUP(ID) ON DELETE CASCADE;
ALTER TABLE GROUP_PATTERN DROP CONSTRAINT GROUP_PATTERN_FK_GROUP;
ALTER TABLE GROUP_PATTERN ADD CONSTRAINT GROUP_PATTERN_FK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES STUDY_GROUP(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP DROP CONSTRAINT STUDY_SUBGROUP_FK_FROMGROUP;
ALTER TABLE SUBGROUP ADD CONSTRAINT STUDY_SUBGROUP_FK_FROMGROUP FOREIGN KEY (RANDOFROMGROUP_ID) REFERENCES STUDY_GROUP(ID) ON DELETE SET NULL;
ALTER TABLE SUBGROUP DROP CONSTRAINT STUDY_SUBGROUP_FK_GROUP;
ALTER TABLE SUBGROUP ADD CONSTRAINT STUDY_SUBGROUP_FK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES STUDY_GROUP(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_LOC_FK;
ALTER TABLE BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES BIOLOCATION(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLING DROP CONSTRAINT FKA466BFE76F86871A;
ALTER TABLE SAMPLING ADD CONSTRAINT SAMPLING_FK_NAMED_SAMPLING FOREIGN KEY (NAMEDSAMPLING_ID) REFERENCES NAMEDSAMPLING(ID) ON DELETE CASCADE;
ALTER TABLE ADMINISTRATION DROP CONSTRAINT ADMINISTRATION_FK_TREATMENT;
ALTER TABLE ADMINISTRATION ADD CONSTRAINT ADMINISTRATION_FK_TREATMENT FOREIGN KEY (NAMED_TREATMENT_ID) REFERENCES NAMEDTREATMENT(ID) ON DELETE CASCADE;
ALTER TABLE SCHEDULE_PHASE DROP CONSTRAINT STUDY_SCHEDULE_PHASE_FK_PHASE;
ALTER TABLE SCHEDULE_PHASE ADD CONSTRAINT STUDY_SCHEDULE_PHASE_FK_PHASE FOREIGN KEY (PHASE_ID) REFERENCES PHASE(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT DROP CONSTRAINT FK3B23D0A3288A7663;
ALTER TABLE ASSAY_RESULT ADD CONSTRAINT ASSAY_RESULT_FK_PHASE FOREIGN KEY (PHASE_ID) REFERENCES PHASE(ID) ON DELETE CASCADE;
ALTER TABLE ADMINISTRATION DROP CONSTRAINT ADMINISTRATION_FK_PHASE;
ALTER TABLE ADMINISTRATION ADD CONSTRAINT ADMINISTRATION_FK_PHASE FOREIGN KEY (PHASE_ID) REFERENCES PHASE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_PHASE_FK;
ALTER TABLE BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_FK_INHERITED_PHASE FOREIGN KEY (INHERITEDPHASE_ID) REFERENCES PHASE(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE DROP CONSTRAINT BIOSAMPLE_ENDPHASE_FK;
ALTER TABLE BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_FK_ENDPHASE FOREIGN KEY (ENDPHASE_ID) REFERENCES PHASE(ID) ON DELETE SET NULL;
ALTER TABLE PROPERTY_LINK DROP CONSTRAINT FK_PROPERTY_LINK_PROPERTY_ID;
ALTER TABLE PROPERTY_LINK ADD CONSTRAINT FK_PROPERTY_LINK_PROPERTY_ID FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE DROP CONSTRAINT FK_SAMPLE_MEASUREMENT_ATTRIBUTE_SAMPLING_MEASUREMENT_ID;
ALTER TABLE SAMPLING_MEASUREMENT_ATTRIBUTE ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_ATTRIBUTE_SAMPLING_MEASUREMENT_ID FOREIGN KEY (SAMPLING_MEASUREMENT_ID) REFERENCES SAMPLING_MEASUREMENT(ID) ON DELETE CASCADE;
ALTER TABLE BIOSAMPLE DROP CONSTRAINT FKBD411C929487B50D;
ALTER TABLE BIOSAMPLE ADD CONSTRAINT BIOSAMPLE_FK_SAMPLING_ID FOREIGN KEY (ATTACHEDSAMPLING_ID) REFERENCES SAMPLING(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLING_MEASUREMENT DROP CONSTRAINT FK_SAMPLE_MEASUREMENT_SAMPLING_ID;
ALTER TABLE SAMPLING_MEASUREMENT ADD CONSTRAINT FK_SAMPLE_MEASUREMENT_SAMPLING_ID FOREIGN KEY (SAMPLING_ID) REFERENCES SAMPLING(ID) ON DELETE CASCADE;
ALTER TABLE SAMPLING_PARAMETER DROP CONSTRAINT FK_SAMPLING_PARAMETER_SAMPLING_ID;
ALTER TABLE SAMPLING_PARAMETER ADD CONSTRAINT FK_SAMPLING_PARAMETER_SAMPLING_ID FOREIGN KEY (SAMPLING_ID) REFERENCES SAMPLING(ID) ON DELETE CASCADE;
ALTER TABLE EXECUTION_DETAILS DROP CONSTRAINT EXECUTION_DETAILS_FK_SCHEDULE_PHASE;
ALTER TABLE EXECUTION_DETAILS ADD CONSTRAINT EXECUTION_DETAILS_FK_SCHEDULE_PHASE FOREIGN KEY (PHASELINK_ID) REFERENCES SCHEDULE_PHASE(ID) ON DELETE CASCADE;
ALTER TABLE SCHEDULE_PHASE DROP CONSTRAINT STUDY_SCHEDULE_PHASE_FK_SCHEDULE;
ALTER TABLE SCHEDULE_PHASE ADD CONSTRAINT STUDY_SCHEDULE_PHASE_FK_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID) ON DELETE CASCADE;
ALTER TABLE ACTIONPATTERNS DROP CONSTRAINT STUDY_ACTIONPATTERN_FK_SCHEDULE;
ALTER TABLE ACTIONPATTERNS ADD CONSTRAINT STUDY_ACTIONPATTERN_FK_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID) ON DELETE CASCADE;
ALTER TABLE STAGE_PATTERN DROP CONSTRAINT STAGE_PATTERN_FK_STAGE;
ALTER TABLE STAGE_PATTERN ADD CONSTRAINT STAGE_PATTERN_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_STAGE_BIOTYPE_METADATAVALUE_FK_STAGE;
ALTER TABLE STAGE_BIOTYPE_METADATAVALUE ADD CONSTRAINT STUDY_STAGE_BIOTYPE_METADATAVALUE_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE PHASE DROP CONSTRAINT STUDY_PHASE_STAGE_FK;
ALTER TABLE PHASE ADD CONSTRAINT PHASE_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE PLANNED_SAMPLE DROP CONSTRAINT FK_PLANNED_SAMPLE_STAGE_ID;
ALTER TABLE PLANNED_SAMPLE ADD CONSTRAINT FK_PLANNED_SAMPLE_STAGE_ID FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENT DROP CONSTRAINT STAGE_ASSIGNMENT_FK_STAGE;
ALTER TABLE ASSIGNMENT ADD CONSTRAINT STAGE_ASSIGNMENT_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE ACTIONPATTERNS DROP CONSTRAINT STUDY_ACTIONPATTERN_FK_STAGE;
ALTER TABLE ACTIONPATTERNS ADD CONSTRAINT STUDY_ACTIONPATTERN_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE STUDY_GROUP DROP CONSTRAINT STUDY_GROUP_FK_STAGE;
ALTER TABLE STUDY_GROUP ADD CONSTRAINT STUDY_GROUP_FK_STAGE FOREIGN KEY (STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
ALTER TABLE STAGE DROP CONSTRAINT STUDY_STAGE_FK_STUDY;
ALTER TABLE STAGE ADD CONSTRAINT STUDY_STAGE_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE PROPERTY_LINK DROP CONSTRAINT FK_PROPERTY_LINK_STUDY_ID;
ALTER TABLE PROPERTY_LINK ADD CONSTRAINT FK_PROPERTY_LINK_STUDY_ID FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE NAMEDTREATMENT DROP CONSTRAINT STUDY_NAMEDTREATMENT_FK_STUDY;
ALTER TABLE NAMEDTREATMENT ADD CONSTRAINT NAMEDTREATMENT_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE NAMEDSAMPLING DROP CONSTRAINT FK2FF629BDFC7F6BA3;
ALTER TABLE NAMEDSAMPLING ADD CONSTRAINT NAMEDSAMPLING_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE ENCLOSURE DROP CONSTRAINT STUDY_ENCLOSURE_FK1;
ALTER TABLE ENCLOSURE ADD CONSTRAINT ENCLOSURE_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE FAVORITE_STUDY DROP CONSTRAINT FK_STUDY_ID;
ALTER TABLE FAVORITE_STUDY ADD CONSTRAINT FAVORITE_STUDY_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE STUDY_DOCUMENT DROP CONSTRAINT FKED922AF1FC7F6BA3;
ALTER TABLE STUDY_DOCUMENT ADD CONSTRAINT STUDY_DOCUMENT_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE ASSAY_RESULT DROP CONSTRAINT RESULT_STUDY_FK;
ALTER TABLE ASSAY_RESULT ADD CONSTRAINT RESULT_FK_STUDY FOREIGN KEY (STUDY_ID) REFERENCES STUDY(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE DROP CONSTRAINT STUDY_SUBGROUP_BIOTYPE_METADATAVALUE_FK_SUBGROUP;
ALTER TABLE SUBGROUP_BIOTYPE_METADATAVALUE ADD CONSTRAINT STUDY_SUBGROUP_BIOTYPE_METADATAVALUE_FK_SUBGROUP FOREIGN KEY (SUBGROUP_ID) REFERENCES SUBGROUP(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP_PATTERN DROP CONSTRAINT SUBGROUP_PATTERN_FK_SUBGROUP;
ALTER TABLE SUBGROUP_PATTERN ADD CONSTRAINT SUBGROUP_PATTERN_FK_SUBGROUP FOREIGN KEY (SUBGROUP_ID) REFERENCES SUBGROUP(ID) ON DELETE CASCADE;
ALTER TABLE ASSIGNMENT DROP CONSTRAINT STAGE_ASSIGNMENT_FK_SUBGROUP;
ALTER TABLE ASSIGNMENT ADD CONSTRAINT ASSIGNMENT_FK_SUBGROUP FOREIGN KEY (SUBGROUP_ID) REFERENCES SUBGROUP(ID) ON DELETE CASCADE;
ALTER TABLE SUBGROUP DROP CONSTRAINT STUDY_SUBGROUP_FK_FROMSUBGROUP;
ALTER TABLE SUBGROUP ADD CONSTRAINT STUDY_SUBGROUP_FK_FROMSUBGROUP FOREIGN KEY (RANDOFROMSUBGROUP_ID) REFERENCES SUBGROUP(ID) ON DELETE CASCADE;
ALTER TABLE BIOLOCATION DROP CONSTRAINT BIOLOCATION_PARENT_FK;
ALTER TABLE BIOLOCATION ADD CONSTRAINT BIOLOCATION_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES BIOLOCATION(ID) ON DELETE CASCADE;